name: Deploy Theme (Secure SFTP)

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Soluciona la advertencia de Node.js

jobs:
  deploy:
    name: Secure SFTP Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Checkout local code
      uses: actions/checkout@v4

    - name: 🚀 Sync files to Hostinger via SFTP
      uses: wlixcc/sftp-deploy-action@v1.5.0
      with:
        username: ${{ secrets.SSH_USER }}
        host: ${{ secrets.SSH_HOST }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: './*' # Sube todo el contenido del tema hijo
        remote_path: '/home/u663435409/domains/ricardoleal.cloud/public_html/wp-content/themes/generatepress-child/'